[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
exclude = ["migrations/*.py"]

[format]
quote-style = "double"
indent-style = "space"
exclude = ["migrations/*.py", 'Makefile']
