"""Create tables categories and transactions

Revision ID: 31db8c22de8c
Revises: 8c7fbf66bd19
Create Date: 2025-08-04 20:10:25.003439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31db8c22de8c"
down_revision: Union[str, Sequence[str], None] = "8c7fbf66bd19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "category_type",
            sa.Enum("debit", "credit", name="categorytypeenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("debit", "credit", name="transactiontypeenum"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("transaction_day_time", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("other_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("categories")
    # ### end Alembic commands ###
