"""Revise transaction_date from datetime to date

Revision ID: 6bcb1cf6c309
Revises: f8ac3a6cdb3d
Create Date: 2025-08-26 21:42:09.427716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6bcb1cf6c309"
down_revision: Union[str, Sequence[str], None] = "f8ac3a6cdb3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("transaction_date", sa.DATE(), nullable=False),
    )
    op.drop_column("transactions", "transaction_day_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "transaction_day_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("transactions", "transaction_date")
    # ### end Alembic commands ###
