"""Added user table, add foreign keys in categories and transaction tables

Revision ID: e867986fa7cd
Revises: 31db8c22de8c
Create Date: 2025-08-05 23:32:26.553781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e867986fa7cd"
down_revision: Union[str, Sequence[str], None] = "31db8c22de8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(length=100), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_foreign_key(None, "categories", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "transactions", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_table("users")
    # ### end Alembic commands ###
